language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - make travis

# Send coverage data to Coveralls
after_script: "cat doc/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
