#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run build
exit 1 # enable to prevent a push when debugging
exit $?


# For git <= 2.9 have to manually hand control over to husky for each hook:
#echo GIT Hook pre-push
#echo ARG1=$1
#echo ARG2=$2
#echo ARG3=$3
[ -x .husky/pre-push ] && .husky/pre-push $1 $2
